### ISSUE TITLE
Did you know you can achieve this easier with Gradle code?

### ISSUE THREAD

**Issue by TWiStErRob** [dansomething/gradle-classpath#3]
If you drop this into any build.gradle.kts:
```kotlin
tasks.register("classpath") {
	outputs.upToDateWhen { false } // Force to always execute.
	doLast {
		val classpath = project.configurations.getByName("runtimeClasspath")
		project.file("build/classpath.txt").writeText(classpath.files.joinToString(":"))
	}
}
```
it provides the same-ish functionality, less parameters, but way less code too :)
Note: the above way of authoring tasks is highly discouraged, but it "just works", however it has none of the Gradle goodies like caching/up-to-date checks, etc.

If you want configurability and full integration, you can do so too with a task:
```kotlin
// build.gradle.kts or in a Gradle Plugin
project.tasks.register<ClasspathPrinterTask>("classpath") {
	// Defaults are set to conventional values, but can be overriden:
	outputFile.set(project.layout.projectDirectory.file("runtimeClasspath.txt"))
}

// anywhere on build classpath
// (`gradlew buildEnvironment`, this includes right next to `register()` in `build.gradle.kts`)
@CacheableTask
abstract class ClasspathPrinterTask : DefaultTask() {
	@get:Option(option = "configuration", description = "Which configuration to dump as classpath.")
	@get:Input
	abstract val configurationName: Property<String>

	@get:Classpath
	abstract val configuration: Property<Configuration>

	@get:OutputFile
	abstract val outputFile: RegularFileProperty

	@get:Input
	abstract val pathSeparator: Property<String>

	init {
		configurationName.convention("runtimeClasspath")
		configuration.convention(project.provider { project.configurations.getByName(configurationName.get()) })
		pathSeparator.convention(":")
		outputFile.convention(project.layout.buildDirectory.file("classpath.txt"))
	}

	@Option(option = "output", description = "Where to put the output file for the classpath.")
	fun setOutputFileLocation(file: String) {
		outputFile.set(project.file(file))
	}

	@TaskAction
	fun printClasspath() {
		println(configurationName.get())
		println(configuration.get().name)
		outputFile.get().asFile.writeText(configuration.get().files.joinToString(pathSeparator.get()))
	}
}
```

This provides automatic checking for changes/input (i.e. `--regenerate-file` equivalent), and even automatic caching. In addition to all the usual Gradle goodies, it also integrates with the CLI, e.g. `gradlew :classpath --configuration=testRuntimeClasspath` will overwrite what configuration to use to resolve the classpath. I tried to use the all the facilities you would need to fully re-write this project. I did this for fun, I was curious how complex it would be to mimic the behaviors of your project.

If you don't want to modify the target projects, you can put this in a Gradle init script and apply to all projects on a specific machine.

**Comment by dansomething** [comment]
Yes, thanks. I am aware of this functionality. It was an option I had considered prior to creating this project. I chose not to go that route to avoid the need to make any changes to Gradle config. That makes this a simple drop-in solution for coc-groovy to use to generate the classpath. A vim user won't need to be aware of its existence when working on their Gradle projects and won't see any changes made to their config. Sure, there is more code here, but it's simple and most of it is there to make it more robust, flexible and easy to use.
